# -*- coding: utf-8 -*-
"""
Created on Sat Nov 16 22:10:02 2019

@author: Roberto Bellarosa
"""

#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Nov 16, 2019 10:43:58 PM CET  platform: Windows NT
import sys
 
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk
   
try:
   import ttk
   py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
   
def set_Tk_var():
   global combobox
   combobox = tk.StringVar()
   
def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
   
def destroy_window():
   # Function which closes the window.
   global top_level
   top_level.destroy()
   top_level = None
   
if __name__ == '__main__':
   import client
   client.vp_start_gui()